---
abstract: 'flash message support'
author:
  - 'Miguel Prz <niceperl@gmail.com>'
build_requires:
  HTTP::Request::Common: 0
  Kelp: 0
  Kelp::Base: 0
  Kelp::Test: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Kelp-Module-FlashMessage
requires:
  Kelp: 0.3102
  Kelp::Module: 0
  Plack: 1.0000
  Plack::Middleware::Session: 0.15
  Test::More: 0
  parent: 0
  strict: 0
  warnings: 0
version: 0.01
